---
title: "async 的使用"
date: 2020-06-07T23:23:57+08:00
draft: false
---

async 的特点

- 它可以和 Promise 结合使用。
- 它能使异步函数更像是同步函数。
- 它的语法和结构会更像是标准的同步函数。

## Promise 的使用

以一个摇色子案例为例：

首先使用一个 Promise 函数封装一个三秒后返回 1 - 6 之间的随机数的函数，然后在调用时使用 `.then()` 方法获取返回的结果，如下：

```js
function fn(){
    return new Promise((resolve, reject)=>{
        setTimeout(()=>{
            /* 产生一个 1-6之间的随机数 */
            let n = parseInt(Math.random() * 6 + 1, 10)
            resolve(n)
        })
    })
}
fn().then(
	(data)=>{ console.log('色子的点数是：'+data) },
    ()=>{ console.log('摇色子失败~') }
)
```

> `Math.random()` 函数返回一个浮点,  从0到1，包含 0 但不包含 1

案例链接：https://codesandbox.io/s/icy-wildflower-29wpi?file=/src/index.js

## async await 的使用

语法首先，await 只能在 async 中使用（强制规定），比如用以下两种方式调用上面的 fn 函数：

```js
let n = await fn() // 语法错误
// 添加到async中:
async function text() {
    let n = await fn() // 不会报错
}
```

将上面的 Promise 中的摇色子案例用 async await 的方式调用，如下：

```js
async function text() {
    let n = await fn() // 注意这里要加括号才会有返回值
    console.log('色子的点数是：'+n)
}
text() // 色子的点数是：3 
```

## 使用 try catch 获取错误

由于在上面的案例中，无法模拟失败，错误的信息，所以我们在摇色子的基础上添加一个猜大小的功能，猜大小函数每次都会判断摇到的筛子是否符合猜测的大小，符合就返回 `resolve()`，不符合就返回 `reject()`，如下：

```js
function 猜大小(猜测){
    return new Promise((resolve, reject)=>{
        setTimeout(()=>{
            let n = parseInt(Math.random()*6+1, 10)
            if(n>3){
                if(猜测==='大'){
                    resolve(n)
                }else{
                    reject(n)
                }
            }else{
                if(猜测==='小'){
                    resolve(n)
                }else{
                    reject(n)
                }
            }
        }, 1000)
    })
}

async function test() {
    try{
        let n = await 猜大小('大')
        console.log('猜对了，点数是'+n)
    } catch (error) {
        console.log('猜错了，点数是'+error)
    }
}
test()
```

上面的代码，如果猜对，就会走 `try{}` 中的内容，如果猜错就会走 `catch(e){}` 中的内容，而错误内容就是 catch 的第一个参数

> Promise 与 async 的优缺点：Promise 的代码更简洁，async 的逻辑更清晰

## Promise.all 的使用

`Promise.all` 接收一个数组，数组里面的每一个函数都会返回一个 Promise。它也可以`.then()`，返回两个函数，第一个函数是必须所有函数都执行成功才会执行，后面一个函数是只要存在一个函数执行失败(或出错)立即执行。

假如我们要调用两次上面的"猜大小"案例，可以使用如下的方法：

```js
Promise.all([猜大小('大'), 猜大小('大')]).then(
    (data)=>{ console.log('猜测成功：'+data) },
    (e)=>{ console.log('猜测失败：'+e) }
)
```

**await + Promise.all 的使用**

用 await 的方式多次调用上面的"猜大小"案例：

```js
async function test() {
    try{
        let n = await Promise.all([猜大小('大'), 猜大小('大')])
        console.log('猜对了，点数是'+n) // 此处的n是一个数组
    } catch (error) {
        console.log('猜错了，点数是'+error)
    }
}
test()
```

